// Cavalry Instance
//
// Creates Cinema 4D-style instances of a selected layer.
// Instances share the source's path, shape geometry, fill, stroke, and all
// other visual attributes. Position, rotation, and scale stay independent.
// Deformers and filters (child layers) are propagated to each instance and
// kept in sync via the Sync button.
//
// Usage:
//   1. Open this script as a panel (Scripting > New Script Panel)
//   2. Select a source layer
//   3. Set an offset so the instance doesn't land on top of the source
//   4. Click Create Instance
//   5. Edit the source layer — all instances update automatically
//   6. To push new deformers/filters to instances, click Sync Deformers
//   7. To break one instance free, select it and click Detach

// ─── Transform attribute filter ───────────────────────────────────────────────

const TRANSFORM_ROOTS = new Set(['position', 'rotation', 'scale']);

function isTransformAttr(key) {
  const root = key.split('.')[0].toLowerCase();
  return TRANSFORM_ROOTS.has(root);
}

// Path attributes generated by the text layout engine — connecting these on a
// text layer causes all characters to stack at the same position.
const TEXT_PATH_ROOTS = new Set(['path', 'editablepath', 'subpath', 'points']);

function isTextPathAttr(key) {
  return TEXT_PATH_ROOTS.has(key.split('.')[0].toLowerCase());
}

// ─── Position helpers ─────────────────────────────────────────────────────────

function getPosition(layerId) {
  try {
    return {
      x: api.get(layerId, 'position.x') ?? 0,
      y: api.get(layerId, 'position.y') ?? 0,
    };
  } catch (_) {
    return { x: 0, y: 0 };
  }
}

function setPosition(layerId, x, y) {
  try {
    api.set(layerId, { 'position.x': x, 'position.y': y });
  } catch (e) {
    console.log(`WARNING: could not set position — ${e.message}`);
  }
}

// ─── Instance tracking ────────────────────────────────────────────────────────

const SOURCE_KEY = 'cavalryInstance_sourceId';

function tagAsInstance(instanceId, sourceId) {
  try { api.setUserData(instanceId, SOURCE_KEY, sourceId); } catch (_) {}
}

function getInstancesOfSource(sourceId) {
  return api.getCompLayers(false).filter(id => {
    try { return api.getUserDataKey(id, SOURCE_KEY) === sourceId; }
    catch (_) { return false; }
  });
}

// ─── Deformer / filter sync ───────────────────────────────────────────────────

// Connect all attributes of a source child layer to a matching instance child.
function connectChildAttrs(sourceChildId, instanceChildId) {
  const keys = api.getAttributes(sourceChildId);
  let connected = 0;
  for (const key of keys) {
    try { api.connect(sourceChildId, key, instanceChildId, key); connected++; }
    catch (_) {}
  }
  return connected;
}

// Propagate child layers (deformers, filters) from source to one instance.
// Skips children that are already present by matching type + name.
function syncChildLayers(sourceId, instanceId) {
  const sourceChildren = api.getChildren(sourceId);
  if (!sourceChildren.length) return 0;

  const existing = new Set(
    api.getChildren(instanceId)
      .map(id => `${api.getLayerType(id)}::${api.getNiceName(id)}`)
  );

  let synced = 0;
  for (const childId of sourceChildren) {
    const childType = api.getLayerType(childId);
    const childName = api.getNiceName(childId);
    if (existing.has(`${childType}::${childName}`)) continue;

    const newChildId = api.create(childType, childName);
    api.parent(newChildId, instanceId);
    connectChildAttrs(childId, newChildId);
    synced++;
  }
  return synced;
}

// Sync deformers/filters from the source to every known instance.
function syncAllDeformers(sourceId) {
  const instances = getInstancesOfSource(sourceId);
  if (!instances.length) {
    console.log('No instances found for this layer. Create instances first.');
    return;
  }
  let total = 0;
  for (const id of instances) total += syncChildLayers(sourceId, id);
  console.log(`Synced ${total} deformer/filter(s) across ${instances.length} instance(s).`);
}

// ─── Core ─────────────────────────────────────────────────────────────────────

function createInstance(sourceId, offsetX, offsetY) {
  const sourceName = api.getNiceName(sourceId) || sourceId;
  const instanceName = `${sourceName} Instance`;
  const layerType = api.getLayerType(sourceId);
  const isText = layerType.toLowerCase().includes('text');

  let instanceId;

  if (layerType === 'editableShape') {
    // Initialise from the source path so the instance starts as the correct
    // shape before attribute connections take over.
    const rawPath = api.getEditablePath(sourceId, false);
    const path = new cavalry.Path();
    path.fromObject(rawPath);
    instanceId = api.createEditable(path, instanceName);
  } else {
    instanceId = api.create(layerType, instanceName);
    // Match generator sub-type (rectangle, circle, star, etc.) so the
    // instance doesn't default to a polygon.
    const gens = api.getGenerators(sourceId);
    for (const g of gens) {
      try {
        api.setGenerator(instanceId, g, api.getCurrentGeneratorType(sourceId, g));
      } catch (_) {}
    }
  }

  // Track this instance so Sync can find it later.
  tagAsInstance(instanceId, sourceId);

  // Mirror fill/stroke enabled state — a blank layer may have these off.
  api.setFill(instanceId, api.hasFill(sourceId));
  api.setStroke(instanceId, api.hasStroke(sourceId));

  // Offset position (not connected — each instance moves independently).
  const srcPos = getPosition(sourceId);
  setPosition(instanceId, srcPos.x + offsetX, srcPos.y + offsetY);

  // Connect every non-transform attribute.
  // For text layers, skip path attributes — the text layout engine generates
  // character paths from the text/font attributes and connecting them directly
  // causes all characters to stack at the same position.
  const keys = api.getAttributes(sourceId);
  let connected = 0;
  for (const key of keys) {
    if (isTransformAttr(key)) continue;
    if (isText && isTextPathAttr(key)) continue;
    try { api.connect(sourceId, key, instanceId, key); connected++; }
    catch (_) {}
  }

  // Propagate any existing deformers / filters from the source.
  const childrenSynced = syncChildLayers(sourceId, instanceId);

  console.log(
    `Instance "${instanceName}" created — ` +
    `${connected} attrs connected, ${childrenSynced} deformer(s) synced.`
  );
  return instanceId;
}

function detachInstance(instanceId) {
  const keys = api.getAttributes(instanceId);
  let detached = 0;
  for (const key of keys) {
    if (isTransformAttr(key)) continue;
    try { api.disconnectInput(instanceId, key); detached++; } catch (_) {}
  }
  const name = api.getNiceName(instanceId) || instanceId;
  console.log(`Detached "${name}" — ${detached} connections removed.`);
}

// ─── UI ──────────────────────────────────────────────────────────────────────

const hintLabel = new ui.Label('Select a source layer, then click Create.');
hintLabel.setFontSize(11);

const offsetXField = new ui.NumericField(150);
offsetXField.setType(0);
offsetXField.setMin(-9999);
offsetXField.setMax(9999);

const offsetYField = new ui.NumericField(0);
offsetYField.setType(0);
offsetYField.setMin(-9999);
offsetYField.setMax(9999);

const createBtn = new ui.Button('Create Instance');
createBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select a source layer before creating an instance.');
    return;
  }
  createInstance(selected[0], offsetXField.getValue(), offsetYField.getValue());
};

const syncBtn = new ui.Button('Sync Deformers to Instances');
syncBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select the source layer to sync from.');
    return;
  }
  syncAllDeformers(selected[0]);
};

const detachBtn = new ui.Button('Detach Selected Instance');
detachBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select an instance layer to detach.');
    return;
  }
  detachInstance(selected[0]);
};

const offsetRow = new ui.HLayout();
offsetRow.setSpaceBetween(6);
offsetRow.add(
  new ui.Label('Offset X'), offsetXField,
  new ui.Label('Y'), offsetYField,
);

const root = new ui.VLayout();
root.setMargins(10, 10, 10, 10);
root.setSpaceBetween(8);
root.add(hintLabel, offsetRow, createBtn, syncBtn, detachBtn);

ui.setTitle('Cavalry Instance');
ui.setMinimumWidth(260);
ui.add(root);
ui.show();
