// Cavalry Instance
//
// Creates Cinema 4D-style instances of a selected layer.
// Instances share the source's path, shape geometry, fill, stroke, and all
// other visual attributes. Position, rotation, and scale stay independent.
// Deformers and filters connected via the Cavalry graph are propagated to
// each instance and can be re-synced after adding new ones.
//
// Usage:
//   1. Open this script as a panel (Scripting > New Script Panel)
//   2. Select a source layer
//   3. Set an offset so the instance doesn't land on top of the source
//   4. Click Create Instance
//   5. Edit the source — all instances update automatically
//   6. After adding a new deformer/filter, click Sync Deformers
//   7. To break one instance free, select it and click Detach

// ─── Transform attribute filter ───────────────────────────────────────────────

const TRANSFORM_ROOTS = new Set(['position', 'rotation', 'scale']);

function isTransformAttr(key) {
  const root = key.split('.')[0].toLowerCase();
  return TRANSFORM_ROOTS.has(root);
}

// ─── Position helpers ─────────────────────────────────────────────────────────

function getPosition(layerId) {
  try {
    return {
      x: api.get(layerId, 'position.x') ?? 0,
      y: api.get(layerId, 'position.y') ?? 0,
    };
  } catch (_) {
    return { x: 0, y: 0 };
  }
}

function setPosition(layerId, x, y) {
  try {
    api.set(layerId, { 'position.x': x, 'position.y': y });
  } catch (e) {
    console.log(`WARNING: could not set position — ${e.message}`);
  }
}

// ─── Instance tracking ────────────────────────────────────────────────────────

const SOURCE_KEY = 'cavalryInstance_sourceId';

function tagAsInstance(instanceId, sourceId) {
  try { api.setUserData(instanceId, SOURCE_KEY, sourceId); } catch (_) {}
}

function getInstancesOfSource(sourceId) {
  return api.getCompLayers(false).filter(id => {
    try { return api.getUserDataKey(id, SOURCE_KEY) === sourceId; }
    catch (_) { return false; }
  });
}

// ─── Fill / stroke sync ───────────────────────────────────────────────────────
// fill and stroke are private attributes — api.connect() cannot reach them.
// Instead we watch for changes via onAttrChanged and propagate with setFill /
// setStroke, which ARE the correct API for these private attributes.

const fillStrokeState = {}; // { sourceId: { fill: bool, stroke: bool } }

function trackFillStroke(sourceId) {
  fillStrokeState[sourceId] = {
    fill:   api.hasFill(sourceId),
    stroke: api.hasStroke(sourceId),
  };
}

function syncFillStroke() {
  for (const sourceId of Object.keys(fillStrokeState)) {
    try {
      const state     = fillStrokeState[sourceId];
      const newFill   = api.hasFill(sourceId);
      const newStroke = api.hasStroke(sourceId);
      if (newFill === state.fill && newStroke === state.stroke) continue;
      state.fill   = newFill;
      state.stroke = newStroke;
      for (const id of getInstancesOfSource(sourceId)) {
        api.setFill(id,   newFill);
        api.setStroke(id, newStroke);
      }
    } catch (_) {}
  }
}

// ─── Deformer / filter sync ───────────────────────────────────────────────────
// Cavalry behaviors connect to target layers via the graph, not parent-child.
// We find them via getInConnectedAttributes and wire the same drivers to instances.

function syncDeformers(sourceId, instanceId) {
  let synced = 0;
  let inAttrs;
  try { inAttrs = api.getInConnectedAttributes(sourceId); }
  catch (_) { inAttrs = []; }

  for (const attr of inAttrs) {
    try {
      const conn = api.getInConnection(sourceId, attr);
      if (!conn) continue;
      const dot = conn.indexOf('.');
      if (dot < 0) continue;
      const fromLayer = conn.slice(0, dot);
      const fromAttr  = conn.slice(dot + 1);
      if (fromLayer === sourceId) continue;
      try { if (api.getInConnection(instanceId, attr)) continue; } catch (_) {}
      api.connect(fromLayer, fromAttr, instanceId, attr);
      synced++;
    } catch (_) {}
  }
  return synced;
}

function syncAllDeformers(sourceId) {
  const instances = getInstancesOfSource(sourceId);
  if (!instances.length) {
    console.log('No instances found for this layer. Create instances first.');
    return;
  }
  let total = 0;
  for (const id of instances) total += syncDeformers(sourceId, id);
  console.log(`Synced ${total} deformer/filter connection(s) across ${instances.length} instance(s).`);
}

// ─── Core ─────────────────────────────────────────────────────────────────────

// Text path roots: generated by the layout engine, not driven by attributes.
// Connecting them directly forces all characters to the same origin.
const TEXT_PATH_ROOTS = new Set(['path', 'editablepath', 'subpath', 'points']);

function createInstance(sourceId, offsetX, offsetY) {
  const sourceName = api.getNiceName(sourceId) || sourceId;
  const instanceName = `${sourceName} Instance`;
  const layerType = api.getLayerType(sourceId);
  const isText = api.hasAttribute(sourceId, 'text');

  let instanceId;

  if (layerType === 'editableShape') {
    const rawPath = api.getEditablePath(sourceId, false);
    const path = new cavalry.Path();
    path.fromObject(rawPath);
    instanceId = api.createEditable(path, instanceName);
  } else {
    instanceId = api.create(layerType, instanceName);
    const gens = api.getGenerators(sourceId);
    for (const g of gens) {
      try {
        api.setGenerator(instanceId, g, api.getCurrentGeneratorType(sourceId, g));
      } catch (_) {}
    }
  }

  tagAsInstance(instanceId, sourceId);

  // fill / stroke: copy current state and start tracking for live updates.
  api.setFill(instanceId,   api.hasFill(sourceId));
  api.setStroke(instanceId, api.hasStroke(sourceId));
  trackFillStroke(sourceId);

  // Offset position (not connected — each instance moves independently).
  const srcPos = getPosition(sourceId);
  setPosition(instanceId, srcPos.x + offsetX, srcPos.y + offsetY);

  const keys = api.getAttributes(sourceId);

  // For text layers: pre-seed every attribute value from source onto the
  // instance BEFORE connecting. This forces the text layout engine to
  // initialise with correct font, tracking, leading, and content so
  // characters are spaced properly from the start.
  if (isText) {
    for (const key of keys) {
      if (isTransformAttr(key)) continue;
      if (TEXT_PATH_ROOTS.has(key.split('.')[0].toLowerCase())) continue;
      try {
        const val = api.get(sourceId, key);
        if (val !== null && val !== undefined) api.set(instanceId, { [key]: val });
      } catch (_) {}
    }
  }

  // Connect all non-transform attributes so the instance mirrors the source.
  let connected = 0;
  for (const key of keys) {
    if (isTransformAttr(key)) continue;
    if (isText && TEXT_PATH_ROOTS.has(key.split('.')[0].toLowerCase())) continue;
    try { api.connect(sourceId, key, instanceId, key); connected++; }
    catch (_) {}
  }

  const deformersSynced = syncDeformers(sourceId, instanceId);

  console.log(
    `Instance "${instanceName}" created — ${connected} attrs connected` +
    (deformersSynced ? `, ${deformersSynced} deformer(s) synced` : '') + '.'
  );
  return instanceId;
}

function detachInstance(instanceId) {
  const keys = api.getAttributes(instanceId);
  let detached = 0;
  for (const key of keys) {
    if (isTransformAttr(key)) continue;
    try { api.disconnectInput(instanceId, key); detached++; } catch (_) {}
  }
  const name = api.getNiceName(instanceId) || instanceId;
  console.log(`Detached "${name}" — ${detached} connections removed.`);
}

// ─── Debug helper ─────────────────────────────────────────────────────────────

function debugLayer(layerId) {
  const name  = api.getNiceName(layerId) || layerId;
  const type  = api.getLayerType(layerId);
  const attrs = api.getAttributes(layerId);
  console.log(`\n=== Debug: "${name}" (${type}) ===`);
  console.log(`  hasFill: ${api.hasFill(layerId)}  hasStroke: ${api.hasStroke(layerId)}`);
  console.log(`  has 'text': ${api.hasAttribute(layerId, 'text')}`);
  console.log(`  attributes (${attrs.length}):`);
  for (const a of attrs) console.log(`    ${a}`);
  console.log('=== end ===\n');
}

// ─── UI ──────────────────────────────────────────────────────────────────────

const hintLabel = new ui.Label('Select a source layer, then click Create.');
hintLabel.setFontSize(11);

const offsetXField = new ui.NumericField(150);
offsetXField.setType(0);
offsetXField.setMin(-9999);
offsetXField.setMax(9999);

const offsetYField = new ui.NumericField(0);
offsetYField.setType(0);
offsetYField.setMin(-9999);
offsetYField.setMax(9999);

const createBtn = new ui.Button('Create Instance');
createBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select a source layer first.');
    return;
  }
  createInstance(selected[0], offsetXField.getValue(), offsetYField.getValue());
};

const syncBtn = new ui.Button('Sync Deformers to Instances');
syncBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select the source layer to sync from.');
    return;
  }
  syncAllDeformers(selected[0]);
};

const detachBtn = new ui.Button('Detach Selected Instance');
detachBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select an instance layer to detach.');
    return;
  }
  detachInstance(selected[0]);
};

const debugBtn = new ui.Button('Debug Selected Layer');
debugBtn.onClick = function () {
  const selected = api.getSelection();
  if (!selected || selected.length === 0) {
    console.log('WARNING: select a layer to debug.');
    return;
  }
  debugLayer(selected[0]);
};

const offsetRow = new ui.HLayout();
offsetRow.setSpaceBetween(6);
offsetRow.add(new ui.Label('Offset X'), offsetXField, new ui.Label('Y'), offsetYField);

const root = new ui.VLayout();
root.setMargins(10, 10, 10, 10);
root.setSpaceBetween(8);
root.add(hintLabel, offsetRow, createBtn, syncBtn, detachBtn, debugBtn);

// Watch for fill/stroke changes on any tracked source layer.
ui.addCallbackObject({ onAttrChanged: syncFillStroke });

ui.setTitle('Cavalry Instance');
ui.setMinimumWidth(260);
ui.add(root);
ui.show();
